### ISSUE TITLE
Gold Caps Quest

### ISSUE THREAD

**Issue by spiderkitten** [teagan75/School-of-Thaumaturgy#1]
Hi, not sure if this is a bug or just me. I have followed the quest book up until the gold caps quest. I scanned in the gold and iron, and unlocked the gold caps in my thaumonomicon and then put 5 gold nuggets in the arcane table, with my wand like the book says. But the table says I do not have enough Vis to make the caps. The little flashing vis symbols say I need around 3.3 of each and I have 30, 17 and 16 of each. I tried looking for tutorials on youtube in case I was doing something wrong but most of them seem to show me needing a research note. Your quest book doesn't mention that. Any advice?

**Comment by teagan75** [comment]
You don't need a research note because I disabled that in the configs and it would only affect you being able to unlock gold caps in your book. Can you take a screenshot of the arcane work table GUI with the nuggets in and your wand. The vis needed is specific.

**Comment by spiderkitten** [comment]
Sure. Here is the table, and also the vis I have. 

arcane table: http://i.imgur.com/kd3XYM3.png
vis: http://i.imgur.com/ftd1JKA.png

**Comment by teagan75** [comment]
It's the terminology that is tripping you up here (thanks Thaumcraft!) Your research table holds aspects. Vis is the charge in your wand. You will need to go to the node room and charge your wand again with Ignis, Terra, and Ordo. Then place it in the arcane table and you will be fine.

**Comment by spiderkitten** [comment]
Ohhhhhh! I feel silly now lol Will go do that. Thank you  :)

**Comment by teagan75** [comment]
Don't feel stupid....Thaumcraft is hard! I will update the quest book to be more specific.
