### ISSUE TITLE
the game keeps crashing

### ISSUE THREAD

**Issue by raynethekiller** [teagan75/School-of-Thaumaturgy#11]
The game keeps crashing when i try to play it. It says play and as soon as I play it I just says sorry for the inconvencene. the game crashed

**Comment by teagan75** [comment]
I need a crash report and/or log

**Comment by raynethekiller** [comment]
Okay. So would I have to send it through the curse since that's where I'm trying to play it?

**Comment by raynethekiller** [comment]
Hopefully this log is the right one you need for the crash report.

    On Monday, April 3, 2017 7:41 PM, teagan75 <notifications@github.com> wrote:
 

 I need a crash report and/or log—

**Comment by teagan75** [comment]
Just give the crash report here

**Comment by raynethekiller** [comment]
It was the GTX 970 video card update was not installed sorry fix her problem.
