### ISSUE TITLE
Disappearing Signs and Invisible Chests

### ISSUE THREAD

**Issue by LilMxPlagueRat** [teagan75/School-of-Thaumaturgy#3]
I decided to explore a little before really getting into the quests and mark off an area using my waypoints every time I saw a sign. However on my way to the dorms some of the signs I had marked off had disappeared (such is the ones in the areas marked Classrooms 6-9). I also noticed some of the chests seemingly disappearing into walls but when you look at the air block next to it it says chest.

**Comment by teagan75** [comment]
I don't know why the signs I put in the school would be disappearing. As for invisible chests, those came with the map. You can break them and replace them. I got rid of a lot of them before I released the pack but not all. Shouldn't affect gameplay.
