### ISSUE TITLE
Quest Issue

### ISSUE THREAD

**Issue by Carmion** [teagan75/School-of-Thaumaturgy#4]
Downloaded the modpack and spent a few hours getting through a considerable chunk of the quests. Logged on today and my quest progress was reset. Anyway i can edit it so i have my quests completed?

**Comment by teagan75** [comment]
Very strange your quests reset. Makes no sense.  If you type /bq_admin edit and it should say "edit mode on."  Open your book and select edit. Then select the category you wish to change. Select 
Designer and click on the quest you want to complete. On the right side, one of the choices are a manual complete. BQ is more complicated than HQM when it comes to this.

**Comment by teagan75** [comment]
Do you have a paid version of Minecraft? Quests are stored by UUID.

**Comment by teagan75** [comment]
#5 Pushing Quests Through
