### ISSUE TITLE
seed?

### ISSUE THREAD

**Issue by RedemptionJokez** [teagan75/School-of-Thaumaturgy#6]
i started this pack and on two occasions i did not spawn at the castle is this my doing or is there a seed that i need?

**Comment by teagan75** [comment]
You either need to get the Official map off the Curse launcher or move it from the template folder to your saves folder.

**Comment by RedemptionJokez** [comment]
i did get it off the curse launcher

**Comment by teagan75** [comment]
Did you get the map of the curse launcher too? You will need to click on the Thaumcraft profile and Add Maps
